version: '2.1'

services:
  lint:
    build: .
    entrypoint: npm run lint
    volumes:
      - ./src:/sqs-quooler/src
      - ./test:/sqs-quooler/test
      - ./package.json:/sqs-quooler/package.json

  test:
    build: .
    entrypoint: npm test
    volumes:
      - ./src:/sqs-quooler/src
      - ./test:/sqs-quooler/test
      - ./package.json:/sqs-quooler/package.json
    depends_on:
      yopa:
        condition: service_healthy

  yopa:
    image: pagarme/yopa:latest
    command: java -Xms64m -Xmx256m -jar uberjar.jar -c /tmp/yopa-in/config.yml -o /tmp/dev-env-aws-regions-override.xml
    ports:
      - 47195
    volumes:
      - ./yopa_config.yml:/tmp/yopa-in/config.yml:ro
    healthcheck:
      test: [
        "CMD-SHELL",
        "curl -f 'http://localhost:47195?Action=GetQueueUrl&QueueName=test'",
        ]
      interval: 5s
      retries: 5
