# YOPA Configuration

# optional configuration: the default values below are used if missing
region: yopa-local
host: yopa
bind-address: 0.0.0.0
sqs:
  port: 80
  # `https` and `host` are used for the regions override XML.
  # This is useful if yopa is fronted by a proxy that offloads HTTPS.
  # https: false
  # host: (defaults to top level `host`:`port`)
  # host: localhost:47195
sns:
  port: 47196
  https: false
s3:
  port: 47197
  https: false
  data-dir: /tmp/yopa-fake-s3/


messaging:
  # creates a queue, not subscribed to any topic
  - sqs://test

